In [1]:
# import libraries
import pandas as pd
from pandas import DataFrame, merge
import numpy as np

In [2]:
# declare variable for first spreadsheet, from USDA website
url = 'https://www.ers.usda.gov/webdocs/DataFiles/53657/table14.xls?v=6753.2'

In [3]:
# declare variable for second spreadsheet from BLS website
url2 = 'https://download.bls.gov/pub/time.series/cu/cu.data.11.USFoodBeverage'

In [4]:
# declare variable for the spreadsheet on BLS website with the series name
url3 = 'https://download.bls.gov/pub/time.series/cu/cu.series'

In [5]:
# create dataframe df
df = pd.read_excel(url, parse_dates=True)

In [6]:
# examine the dataframe
df.head(10)

,"Table 14--Fuel ethanol, corn, and gasoline prices, by month",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Corn,Ethanol,Blender cost of ethanol with credit1,Gasoline,Corn cost per gallon ethanol2,Ethanol geg3
2,NaN,$ / bu.,$ / gal.,$ / gal.,$ / gal.,$ / gal.,$ / geg
3,1982-01-01 00:00:00,2.54,1.75,1.15,1.04,0.940741,2.61194
4,1982-02-01 00:00:00,2.44,1.7,1.1,1.01,0.903704,2.53731
5,1982-03-01 00:00:00,2.46,1.66,1.06,0.95,0.911111,2.47761
6,1982-04-01 00:00:00,2.55,1.7,1.1,0.9,0.944444,2.53731
7,1982-05-01 00:00:00,2.6,1.7,1.1,0.94,0.962963,2.53731
8,1982-06-01 00:00:00,2.57,1.7,1.1,1.05,0.951852,2.53731
9,1982-07-01 00:00:00,2.5,1.7,1.1,1.06,0.925926,2.53731

In [7]:
df.tail(10)

,"Table 14--Fuel ethanol, corn, and gasoline prices, by month",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
463,May-20,3.2,0.75,0.75,1.06,0.277778,1.1194
464,Jun-20,NaN,0.85,0.85,1.3,0.314815,1.26866
465,Note: Corn prices received by farmers. Ethanol...,NaN,NaN,NaN,NaN,NaN,NaN
466,NA = not available.,NaN,NaN,NaN,NaN,NaN,NaN
467,1Blenders tax credit: $0.60 per gallon through...,NaN,NaN,NaN,NaN,NaN,NaN
468,2 Based on one bushel of corn yielding 2.7 gal...,NaN,NaN,NaN,NaN,NaN,NaN
469,3geg = gasoline equivalent gallons. A gallon ...,NaN,NaN,NaN,NaN,NaN,NaN
470,NaN,NaN,NaN,NaN,NaN,NaN,NaN
471,"Sources: USDA, Economic Research Service based...",NaN,NaN,NaN,NaN,NaN,NaN
472,Updated July 2020.,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# re-write column headers
df.columns = ['Month_Year', 'Corn', 'Ethanol','Blender_cost', 'Gasoline', 'Corn_cost_per_gallon', 'Ethanol_geg']

In [9]:
# drop the first three rows and last eight rows
df1 = df.drop(df.index[0:3]).drop(df.index[-8:])

In [10]:
# examine df1
df1

,Month_Year,Corn,Ethanol,Blender_cost,Gasoline,Corn_cost_per_gallon,Ethanol_geg
3,1982-01-01 00:00:00,2.54,1.75,1.15,1.04,0.940741,2.61194
4,1982-02-01 00:00:00,2.44,1.7,1.1,1.01,0.903704,2.53731
5,1982-03-01 00:00:00,2.46,1.66,1.06,0.95,0.911111,2.47761
6,1982-04-01 00:00:00,2.55,1.7,1.1,0.9,0.944444,2.53731
7,1982-05-01 00:00:00,2.6,1.7,1.1,0.94,0.962963,2.53731
...,...,...,...,...,...,...,...
460,Feb-20,3.78,1.03,1.03,1.78,0.381481,1.53731
461,Mar-20,3.68,0.84,0.84,1.14,0.311111,1.25373
462,Apr-20,3.29,0.59,0.59,0.63,0.218519,0.880597
463,May-20,3.2,0.75,0.75,1.06,0.277778,1.1194
464,Jun-20,NaN,0.85,0.85,1.3,0.314815,1.26866

In [11]:
# create an empty list that will become a field in df1 representing month
Month = []

In [12]:
# create an empty list that will become a field in df1 representing year
Year = []

In [13]:
for i in range(0, 462):
    if len(Month) % 12 == 0:
        Month.append(1)
    else:
        Month.append(Month[-1] + 1)

In [14]:
for i in range(0, 462):
    if len(Year) == 0:
        Year.append(1982)
    elif len(Year) % 12 == 0:
        Year.append(Year[-1] + 1)
    else:
        Year.append(Year[-1])

In [15]:
# add the year column to df1
df1['Year'] = Year

In [16]:
# add the month column to df1
df1['Month'] = Month

In [17]:
# create dataframe cpi
cpi = pd.read_csv(url2, delimiter="\t")

In [18]:
# create dataframe cpi_key
cpi_key = pd.read_csv(url3, delimiter="\t")

In [19]:
# examine columns
cpi_key.columns

Index(['series_id        ', 'area_code', 'item_code', 'seasonal',
       'periodicity_code', 'base_code', 'base_period', 'series_title',
       'footnote_codes', 'begin_year', 'begin_period', 'end_year',
       'end_period'],
      dtype='object')

In [20]:
# examine cpi
cpi

        series_id          year period         value  footnote_codes
0       CUSR0000SAF        1967    M01        34.800             NaN
1       CUSR0000SAF        1967    M02        34.700             NaN
2       CUSR0000SAF        1967    M03        34.700             NaN
3       CUSR0000SAF        1967    M04        34.600             NaN
4       CUSR0000SAF        1967    M05        34.600             NaN
...                   ...   ...    ...           ...             ...
134450  CUUSS000SEFV       2018    S03       239.016             NaN
134451  CUUSS000SEFV       2019    S01       244.880             NaN
134452  CUUSS000SEFV       2019    S02       248.774             NaN
134453  CUUSS000SEFV       2019    S03       246.827             NaN
134454  CUUSS000SEFV       2020    S01       253.039             NaN

[134455 rows x 5 columns]

In [21]:
# merge the cpi and cpi_key to lookup the series title corresponding with a given series_id
cpi2 = pd.merge(cpi, cpi_key[['series_id        ','series_title']], on='series_id        ', how='left')

In [22]:
# examine cpi2
cpi2

,series_id,year,period,value,footnote_codes,series_title
0,CUSR0000SAF,1967,M01,34.800,NaN,"Food and beverages in U.S. city average, all u..."
1,CUSR0000SAF,1967,M02,34.700,NaN,"Food and beverages in U.S. city average, all u..."
2,CUSR0000SAF,1967,M03,34.700,NaN,"Food and beverages in U.S. city average, all u..."
3,CUSR0000SAF,1967,M04,34.600,NaN,"Food and beverages in U.S. city average, all u..."
4,CUSR0000SAF,1967,M05,34.600,NaN,"Food and beverages in U.S. city average, all u..."
...,...,...,...,...,...,...
134450,CUUSS000SEFV,2018,S03,239.016,NaN,"Food away from home in Size Class A, all urban..."
134451,CUUSS000SEFV,2019,S01,244.880,NaN,"Food away from home in Size Class A, all urban..."
134452,CUUSS000SEFV,2019,S02,248.774,NaN,"Food away from home in Size Class A, all urban..."
134453,CUUSS000SEFV,2019,S03,246.827,NaN,"Food away from home in Size Class A, all urban..."
134454,CUUSS000SEFV,2020,S01,253.039,NaN,"Food away from home in Size Class A, all urban..."

In [23]:
# extract only the numbers from the period field and convert to integer
# per https://download.bls.gov/pub/time.series/cu/cu.period, values in period with a M01-M12 are months, M13 is annual average. S01 is first half of year, S02 is second half of year, S03 is annual average
cpi_month = cpi2.period.str[1:].astype(int)

In [24]:
# create a cpi_period_type to differentiate between "m" for "month" (1-13 where 13 is annual average), and "s" for "semi-annual"
cpi_period_type = cpi2.period.str[0]

In [25]:
# add month to the cpi2 dataframe
cpi2['cpi_month'] = cpi_month

In [26]:
# add period_type to the cpi2 dataframe
cpi2['cpi_period_type'] = cpi_period_type

In [27]:
#examine cpi2
cpi2

,series_id,year,period,value,footnote_codes,series_title,cpi_month,cpi_period_type
0,CUSR0000SAF,1967,M01,34.800,NaN,"Food and beverages in U.S. city average, all u...",1,M
1,CUSR0000SAF,1967,M02,34.700,NaN,"Food and beverages in U.S. city average, all u...",2,M
2,CUSR0000SAF,1967,M03,34.700,NaN,"Food and beverages in U.S. city average, all u...",3,M
3,CUSR0000SAF,1967,M04,34.600,NaN,"Food and beverages in U.S. city average, all u...",4,M
4,CUSR0000SAF,1967,M05,34.600,NaN,"Food and beverages in U.S. city average, all u...",5,M
...,...,...,...,...,...,...,...,...
134450,CUUSS000SEFV,2018,S03,239.016,NaN,"Food away from home in Size Class A, all urban...",3,S
134451,CUUSS000SEFV,2019,S01,244.880,NaN,"Food away from home in Size Class A, all urban...",1,S
134452,CUUSS000SEFV,2019,S02,248.774,NaN,"Food away from home in Size Class A, all urban...",2,S
134453,CUUSS000SEFV,2019,S03,246.827,NaN,"Food away from home in Size Class A, all urban...",3,S
134454,CUUSS000SEFV,2020,S01,253.039,NaN,"Food away from home in Size Class A, all urban...",1,S

In [28]:
# remove any values that are not "m"
cpi_m = cpi2.drop(cpi2[cpi2['cpi_period_type'] != 'M'].index)

In [29]:
# ensure that all values for cpi_period_type are m
cpi_m.cpi_period_type.value_counts()

M    131715
Name: cpi_period_type, dtype: int64

In [30]:
# create a pivot table so that the year/month combined represents a row, and that each price category is a column
cpi_pt =  pd.pivot_table(cpi_m, values='       value', index=['year', 'cpi_month'], columns=['series_title'])

In [31]:
# examine the pivot table
cpi_pt.loc[(1982,1)]['Poultry in U.S. city average, all urban consumers, not seasonally adjusted']

95.3

In [32]:
# check percentage of missing data since 1982
for i in cpi_pt.columns:
    not_missing = cpi_pt.loc[1982:][i].count()
    col_size = len(cpi_pt.loc[1982:][i])
    percent_unique_values = "{:.2%}".format(not_missing/col_size)
    print(i + ' : ' + percent_unique_values)

Alcoholic beverages at home in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Alcoholic beverages at home in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Alcoholic beverages away from home in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Alcoholic beverages away from home in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Alcoholic beverages in Size Class A, all urban consumers, not seasonally adjusted : 87.20%
Alcoholic beverages in Size Class B/C, all urban consumers, not seasonally adjusted : 58.60%
Alcoholic beverages in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Alcoholic beverages in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Apples in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Apples in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Baby food in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Bacon and related products in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Bacon and related products in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Bacon, breakfast sausage, and related products in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Bacon, breakfast sausage, and related products in U.S. city average, all urban consumers, seasonally adjusted : 54.00%
Bakery products in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Bakery products in U.S. city average, all urban consumers, seasonally adjusted : 68.40%
Bananas in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Bananas in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Beef and veal in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Beef and veal in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Beer, ale, and other malt beverages at home in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Beer, ale, and other malt beverages at home in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Beer, ale, and other malt beverages away from home in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Beverage materials including coffee and tea in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Beverage materials including coffee and tea in U.S. city average, all urban consumers, seasonally adjusted : 54.00%
Bread in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Bread in U.S. city average, all urban consumers, seasonally adjusted : 37.20%
Bread other than white in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Breakfast cereal in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Breakfast cereal in U.S. city average, all urban consumers, seasonally adjusted : 68.40%
Breakfast sausage and related products in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Breakfast sausage and related products in U.S. city average, all urban consumers, seasonally adjusted : 54.00%
Butter and margarine in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Butter and margarine in U.S. city average, all urban consumers, seasonally adjusted : 44.40%
Butter in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Butter in U.S. city average, all urban consumers, seasonally adjusted : 63.60%
Cakes, cupcakes, and cookies in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Cakes, cupcakes, and cookies in U.S. city average, all urban consumers, seasonally adjusted : 58.80%
Candy and chewing gum in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Canned fruits and vegetables in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Canned fruits and vegetables in U.S. city average, all urban consumers, seasonally adjusted : 54.00%
Canned fruits in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Canned fruits in U.S. city average, all urban consumers, seasonally adjusted : 42.00%
Canned vegetables in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Canned vegetables in U.S. city average, all urban consumers, seasonally adjusted : 51.60%
Carbonated drinks in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Carbonated drinks in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Cereals and bakery products in Size Class A, all urban consumers, not seasonally adjusted : 6.80%
Cereals and bakery products in Size Class B/C, all urban consumers, not seasonally adjusted : 6.80%
Cereals and bakery products in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Cereals and bakery products in U.S. city average, all urban consumers, seasonally adjusted : 75.60%
Cereals and cereal products in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Cereals and cereal products in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Cheese and related products in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Cheese and related products in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Chicken in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Chicken in U.S. city average, all urban consumers, seasonally adjusted : 39.60%
Citrus fruits in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Citrus fruits in U.S. city average, all urban consumers, seasonally adjusted : 54.00%
Coffee in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Coffee in U.S. city average, all urban consumers, seasonally adjusted : 42.00%
Cookies in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Cookies in U.S. city average, all urban consumers, seasonally adjusted : 73.20%
Crackers, bread, and cracker products in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Crackers, bread, and cracker products in U.S. city average, all urban consumers, seasonally adjusted : 66.00%
Dairy and related products in Size Class A, all urban consumers, not seasonally adjusted : 6.80%
Dairy and related products in Size Class B/C, all urban consumers, not seasonally adjusted : 6.80%
Dairy and related products in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Dairy and related products in U.S. city average, all urban consumers, seasonally adjusted : 75.60%
Distilled spirits at home in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Distilled spirits at home in U.S. city average, all urban consumers, seasonally adjusted : 68.40%
Distilled spirits away from home in U.S. city average, all urban consumers, not seasonally adjusted : 58.20%
Distilled spirits away from home in U.S. city average, all urban consumers, seasonally adjusted : 53.60%
Distilled spirits, excluding whiskey, at home in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Distilled spirits, excluding whiskey, at home in U.S. city average, all urban consumers, seasonally adjusted : 51.60%
Dried beans, peas, and lentils in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Eggs in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Eggs in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Fats and oils in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Fats and oils in U.S. city average, all urban consumers, seasonally adjusted : 75.60%
Fish and seafood in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Fish and seafood in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Flour and prepared flour mixes in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Flour and prepared flour mixes in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Food and beverages in Size Class A, all urban consumers, not seasonally adjusted : 87.20%
Food and beverages in Size Class B/C, all urban consumers, not seasonally adjusted : 58.60%
Food and beverages in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Food and beverages in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Food at employee sites and schools in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Food at employee sites and schools in U.S. city average, all urban consumers, seasonally adjusted : 54.00%
Food at home in Size Class A, all urban consumers, not seasonally adjusted : 87.20%
Food at home in Size Class B/C, all urban consumers, not seasonally adjusted : 58.60%
Food at home in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Food at home in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Food away from home in Size Class A, all urban consumers, not seasonally adjusted : 87.20%
Food away from home in Size Class B/C, all urban consumers, not seasonally adjusted : 58.60%
Food away from home in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Food away from home in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Food from vending machines and mobile vendors in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Food in Size Class A, all urban consumers, not seasonally adjusted : 87.20%
Food in Size Class B/C, all urban consumers, not seasonally adjusted : 58.60%
Food in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Food in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Frankfurters in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Frankfurters in U.S. city average, all urban consumers, seasonally adjusted : 44.40%
Fresh and frozen chicken parts in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Fresh biscuits, rolls, muffins in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Fresh biscuits, rolls, muffins in U.S. city average, all urban consumers, seasonally adjusted : 32.40%
Fresh cakes and cupcakes in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Fresh fish and seafood in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Fresh fish and seafood in U.S. city average, all urban consumers, seasonally adjusted : 25.20%
Fresh fruits and vegetables in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Fresh fruits and vegetables in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Fresh fruits in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Fresh fruits in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Fresh milk other than whole in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Fresh milk other than whole in U.S. city average, all urban consumers, seasonally adjusted : 22.80%
Fresh sweetrolls, coffeecakes, doughnuts in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Fresh vegetables in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Fresh vegetables in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Fresh whole chicken in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Fresh whole chicken in U.S. city average, all urban consumers, seasonally adjusted : 63.60%
Fresh whole milk in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Fresh whole milk in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Frozen and freeze dried prepared foods in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Frozen and freeze dried prepared foods in U.S. city average, all urban consumers, seasonally adjusted : 49.20%
Frozen and refrigerated bakery products, pies, tarts, turnovers in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Frozen and refrigerated bakery products, pies, tarts, turnovers in U.S. city average, all urban consumers, seasonally adjusted : 61.20%
Frozen fish and seafood in U.S. city average, all urban consumers, not seasonally adjusted : 96.60%
Frozen fish and seafood in U.S. city average, all urban consumers, seasonally adjusted : 89.40%
Frozen fruits and vegetables in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Frozen fruits and vegetables in U.S. city average, all urban consumers, seasonally adjusted : 54.00%
Frozen noncarbonated juices and drinks in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Frozen vegetables in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Frozen vegetables in U.S. city average, all urban consumers, seasonally adjusted : 70.80%
Fruits and vegetables in Size Class A, all urban consumers, not seasonally adjusted : 6.80%
Fruits and vegetables in Size Class B/C, all urban consumers, not seasonally adjusted : 6.80%
Fruits and vegetables in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Fruits and vegetables in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Full service meals and snacks in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Full service meals and snacks in U.S. city average, all urban consumers, seasonally adjusted : 54.00%
Ham in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Ham in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Ham, excluding canned in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Ham, excluding canned in U.S. city average, all urban consumers, seasonally adjusted : 78.00%
Ice cream and related products in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Ice cream and related products in U.S. city average, all urban consumers, seasonally adjusted : 73.20%
Instant coffee in U.S. city average, all urban consumers, not seasonally adjusted : 97.40%
Juices and nonalcoholic drinks in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Juices and nonalcoholic drinks in U.S. city average, all urban consumers, seasonally adjusted : 54.00%
Lamb and mutton in U.S. city average, all urban consumers, not seasonally adjusted : 36.60%
Lamb and organ meats in U.S. city average, all urban consumers, not seasonally adjusted : 90.60%
Lettuce in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Lettuce in U.S. city average, all urban consumers, seasonally adjusted : 34.80%
Limited service meals and snacks in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Lunchmeats in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Lunchmeats in U.S. city average, all urban consumers, seasonally adjusted : 25.20%
Margarine in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Margarine in U.S. city average, all urban consumers, seasonally adjusted : 63.60%
Meats in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Meats in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Meats, poultry, and fish in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Meats, poultry, and fish in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Meats, poultry, fish, and eggs in Size Class A, all urban consumers, not seasonally adjusted : 6.80%
Meats, poultry, fish, and eggs in Size Class B/C, all urban consumers, not seasonally adjusted : 6.80%
Meats, poultry, fish, and eggs in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Meats, poultry, fish, and eggs in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Milk in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Milk in U.S. city average, all urban consumers, seasonally adjusted : 51.60%
Nonalcoholic beverages and beverage materials in Size Class A, all urban consumers, not seasonally adjusted : 6.80%
Nonalcoholic beverages and beverage materials in Size Class B/C, all urban consumers, not seasonally adjusted : 6.80%
Nonalcoholic beverages and beverage materials in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Nonalcoholic beverages and beverage materials in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Nonfrozen noncarbonated juices and drinks in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Nonfrozen noncarbonated juices and drinks in U.S. city average, all urban consumers, seasonally adjusted : 25.20%
Olives, pickles, relishes in U.S. city average, all urban consumers, not seasonally adjusted : 57.40%
Oranges, including tangerines in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Oranges, including tangerines in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Other bakery products in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Other bakery products in U.S. city average, all urban consumers, seasonally adjusted : 87.60%
Other beverage materials including tea in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Other beverage materials including tea in U.S. city average, all urban consumers, seasonally adjusted : 42.00%
Other condiments in U.S. city average, all urban consumers, not seasonally adjusted : 99.00%
Other condiments in U.S. city average, all urban consumers, seasonally adjusted : 77.00%
Other dairy and related products in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Other dairy and related products in U.S. city average, all urban consumers, seasonally adjusted : 42.00%
Other fats and oils including peanut butter in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Other fats and oils including peanut butter in U.S. city average, all urban consumers, seasonally adjusted : 42.00%
Other food at home in Size Class A, all urban consumers, not seasonally adjusted : 6.80%
Other food at home in Size Class B/C, all urban consumers, not seasonally adjusted : 6.80%
Other food at home in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Other food at home in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Other food away from home in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Other food away from home in U.S. city average, all urban consumers, seasonally adjusted : 54.00%
Other foods in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Other foods in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Other fresh fruits in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Other fresh fruits in U.S. city average, all urban consumers, seasonally adjusted : 54.00%
Other fresh vegetables in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Other fresh vegetables in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Other meats in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Other meats in U.S. city average, all urban consumers, seasonally adjusted : 56.40%
Other miscellaneous foods in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%

Potatoes in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Poultry in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Poultry in U.S. city average, all urban consumers, seasonally adjusted : 54.00%
Prepared salads in U.S. city average, all urban consumers, not seasonally adjusted : 32.60%
Processed fish and seafood in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Processed fish and seafood in U.S. city average, all urban consumers, seasonally adjusted : 54.00%
Processed fruits and vegetables in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Processed fruits and vegetables in U.S. city average, all urban consumers, seasonally adjusted : 54.00%
Rice in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Rice, pasta, cornmeal in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Rice, pasta, cornmeal in U.S. city average, all urban consumers, seasonally adjusted : 73.20%
Roasted coffee in U.S. city average, all urban consumers, not seasonally adjusted : 97.40%
Roasted coffee in U.S. city average, all urban consumers, seasonally adjusted : 44.40%
Salad dressing in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Salad dressing in U.S. city average, all urban consumers, seasonally adjusted : 54.00%
Salt and other seasonings and spices in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Salt and other seasonings and spices in U.S. city average, all urban consumers, seasonally adjusted : 34.80%
Sauces and gravies in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Sauces and gravies in U.S. city average, all urban consumers, seasonally adjusted : 34.80%
Shelf stable fish and seafood in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Shelf stable fish and seafood in U.S. city average, all urban consumers, seasonally adjusted : 63.60%
Snacks in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Snacks in U.S. city average, all urban consumers, seasonally adjusted : 85.20%
Soups in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Soups in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Spices, seasonings, condiments, sauces in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Spices, seasonings, condiments, sauces in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Sugar and artificial sweeteners in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Sugar and artificial sweeteners in U.S. city average, all urban consumers, seasonally adjusted : 75.60%
Sugar and sweets in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Sugar and sweets in U.S. city average, all urban consumers, seasonally adjusted : 75.60%
Tomatoes in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Tomatoes in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Uncooked beef roasts in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Uncooked beef steaks in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Uncooked beef steaks in U.S. city average, all urban consumers, seasonally adjusted : 54.00%
Uncooked ground beef in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Uncooked ground beef in U.S. city average, all urban consumers, seasonally adjusted : 92.40%
Uncooked other beef and veal in U.S. city average, all urban consumers, not seasonally adjusted : 58.60%
Whiskey at home in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Whiskey at home in U.S. city average, all urban consumers, seasonally adjusted : 63.60%
White bread in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Wine at home in U.S. city average, all urban consumers, not seasonally adjusted : 100.00%
Wine at home in U.S. city average, all urban consumers, seasonally adjusted : 73.20%
Wine away from home in U.S. city average, all urban consumers, not seasonally adjusted : 58.00%

In [33]:
# I selected the series that I will use for this study that cover a wide range of food products, 
# and only not-seasonally adjusted to match the ethanol information, and where there is complete data since 1982
sel_cols = ['Alcoholic beverages at home in U.S. city average, all urban consumers, not seasonally adjusted', 'Cakes, cupcakes, and cookies in U.S. city average, all urban consumers, not seasonally adjusted', 'Carbonated drinks in U.S. city average, all urban consumers, not seasonally adjusted', 'Breakfast cereal in U.S. city average, all urban consumers, not seasonally adjusted', 'Cereals and cereal products in U.S. city average, all urban consumers, not seasonally adjusted', 'Fats and oils in U.S. city average, all urban consumers, not seasonally adjusted', 'Fish and seafood in U.S. city average, all urban consumers, not seasonally adjusted', 'Flour and prepared flour mixes in U.S. city average, all urban consumers, not seasonally adjusted', 'Food in U.S. city average, all urban consumers, not seasonally adjusted', 'Frozen vegetables in U.S. city average, all urban consumers, not seasonally adjusted', 'Fruits and vegetables in U.S. city average, all urban consumers, not seasonally adjusted', 'Meats in U.S. city average, all urban consumers, not seasonally adjusted', 'Poultry in U.S. city average, all urban consumers, not seasonally adjusted', 'Dairy and related products in U.S. city average, all urban consumers, not seasonally adjusted','Ham in U.S. city average, all urban consumers, not seasonally adjusted'
,'Beef and veal in U.S. city average, all urban consumers, not seasonally adjusted','Rice, pasta, cornmeal in U.S. city average, all urban consumers, not seasonally adjusted']

In [34]:
# Drop all columns that are not on the list of sel_cols
cpi_p = cpi_pt.drop(cpi_pt.iloc[:,cpi_pt.columns.isin(sel_cols)==False], axis=1)

In [35]:
#drop all values before 1982
# question - why does this not work: cpi_f = cpi_p.drop(cpi_p.loc[:(1982,1)])
cpi_f = cpi_p.drop(cpi_p.index[:897])

In [36]:
cpi_f

series_title    Alcoholic beverages at home in U.S. city average, all urban consumers, not seasonally adjusted  \
year cpi_month
1982 1                                                     95.000
     2                                                     95.800
     3                                                     96.300
     4                                                     96.700
     5                                                     97.000
...                                                           ...
2020 2                                                    207.030
     3                                                    208.219
     4                                                    209.282
     5                                                    209.557
     6                                                    209.412

series_title    Beef and veal in U.S. city average, all urban consumers, not seasonally adjusted  \
year cpi_month
1982 1                                                     98.000
     2                                                     98.800
     3                                                     98.900
     4                                                    100.000
     5                                                    102.300
...                                                           ...
2020 2                                                    314.232
     3                                                    316.270
     4                                                    329.503
     5                                                    365.484
     6                                                    385.495

series_title    Breakfast cereal in U.S. city average, all urban consumers, not seasonally adjusted  \
year cpi_month
1982 1                                                     93.100
     2                                                     94.100
     3                                                     94.300
     4                                                     94.400
     5                                                     94.600
...                                                           ...
2020 2                                                    217.695
     3                                                    221.578
     4                                                    224.844
     5                                                    228.013
     6                                                    230.490

series_title    Cakes, cupcakes, and cookies in U.S. city average, all urban consumers, not seasonally adjusted  \
year cpi_month
1982 1                                                     94.200
     2                                                     94.400
     3                                                     94.800
     4                                                     95.200
     5                                                     95.500
...                                                           ...
2020 2                                                    288.073
     3                                                    292.379
     4                                                    296.846
     5                                                    294.435
     6                                                    298.935

series_title    Carbonated drinks in U.S. city average, all urban consumers, not seasonally adjusted  \
year cpi_month
1982 1                                                     96.700
     2                                                     97.600
     3                                                     98.000
     4                                                     97.600
     5                                                     98.100
...                                                           ...
2020 2                                                    173.629
     3                                                    175.423
     4                                                    181.539
     5                                                    179.466
     6                                                    182.446

series_title    Cereals and cereal products in U.S. city average, all urban consumers, not seasonally adjusted  \
year cpi_month
1982 1                                                     96.800
     2                                                     97.500
     3                                                     97.400
     4                                                     97.200
     5                                                     97.800
...                                                           ...
2020 2                                                    226.169
     3                                                    228.033
     4                                                    232.267
     5                                                    235.715
     6                                                    236.930

series_title    Dairy and related products in U.S. city average, all urban consumers, not seasonally adjusted  \
year cpi_month
1982 1                                                     98.300
     2                                                     98.600
     3                                                     98.600
     4                                                     99.000
     5                                                     98.800
...                                                           ...
2020 2                                                    224.443
     3                                                    225.627
     4                                                    228.755
     5                                                    230.166
     6                                                    228.437

series_title    Fats and oils in U.S. city average, all urban consumers, not seasonally adjusted  \
year cpi_month
1982 1                                                     96.800
     2                                                     96.400
     3                                                     96.100
     4                                                     96.400
     5                                                     96.400
...                                                           ...
2020 2                                                    226.890
     3                                                    228.497
     4                                                    230.824
     5                                                    231.069
     6                                                    230.438

series_title    Fish and seafood in U.S. city average, all urban consumers, not seasonally adjusted  \
year cpi_month
1982 1                                                     98.900
     2                                                     99.000
     3                                                     99.700
     4                                                    101.200
     5                                                     97.000
...                                                           ...
2020 2                                                    298.721
     3                                                    297.550
     4                                                    311.987
     5                                                    313.424
     6                                                    310.716

series_title    Flour and prepared flour mixes in U.S. city average, all urban consumers, not seasonally adjusted  \
year cpi_month
1982 1                                                     97.800
     2                                                     97.800
     3                                                     97.900
     4                                                     98.200
     5                                                     99.700
...                                                           ...
2020 2                                                    234.170
     3                                                    235.939
     4                                                    238.985
     5                                                    240.779
     6                                                    244.665

series_title    Food in U.S. city average, all urban consumers, not seasonally adjusted  \
year cpi_month
1982 1                                                     95.800
     2                                                     96.600
     3                                                     96.400
     4                                                     96.800
     5                                                     97.300
...                                                           ...
2020 2                                                    261.876
     3                                                    262.708
     4                                                    266.757
     5                                                    268.439
     6                                                    269.770

series_title    Frozen vegetables in U.S. city average, all urban consumers, not seasonally adjusted  \
year cpi_month
1982 1                                                     93.300
     2                                                     94.000
     3                                                     94.200
     4                                                     95.500
     5                                                     95.500
...                                                           ...
2020 2                                                    201.604
     3                                                    201.175
     4                                                    207.732
     5                                                    209.380
     6                                                    210.497

series_title    Fruits and vegetables in U.S. city average, all urban consumers, not seasonally adjusted  \
year cpi_month
1982 1                                                     98.100
     2                                                    100.400
     3                                                     97.600
     4                                                     97.900
     5                                                     99.200
...                                                           ...
2020 2                                                    299.817
     3                                                    299.641
     4                                                    304.809
     5                                                    306.798
     6                                                    305.393

series_title    Ham in U.S. city average, all urban consumers, not seasonally adjusted  \
year cpi_month
1982 1                                                     94.400
     2                                                     94.300
     3                                                     95.800
     4                                                     93.400
     5                                                     97.100
...                                                           ...
2020 2                                                    209.558
     3                                                    219.842
     4                                                    210.336
     5                                                    221.910
     6                                                    227.745

series_title    Meats in U.S. city average, all urban consumers, not seasonally adjusted  \
year cpi_month
1982 1                                                     96.000
     2                                                     96.900
     3                                                     97.300
     4                                                     98.200
     5                                                    100.400
...                                                           ...
2020 2                                                    260.417
     3                                                    261.489
     4                                                    270.149
     5                                                    286.185
     6                                                    298.033

series_title    Poultry in U.S. city average, all urban consumers, not seasonally adjusted  \
year cpi_month
1982 1                                                     95.300
     2                                                     96.100
     3                                                     95.600
     4                                                     94.900
     5                                                     96.200
...                                                           ...
2020 2                                                    232.820
     3                                                    235.803
     4                                                    246.991
     5                                                    252.418
     6                                                    252.765

series_title    Rice, pasta, cornmeal in U.S. city average, all urban consumers, not seasonally adjusted
year cpi_month
1982 1                                                    102.000
     2                                                    102.900
     3                                                    102.100
     4                                                    101.000
     5                                                    101.400
...                                                           ...
2020 2                                                    239.446
     3                                                    238.912
     4                                                    244.852
     5                                                    249.304
     6                                                    248.073

[500 rows x 17 columns]

In [37]:
#combine the USDA dataframe with the CPI data by joining on year and month
combined = pd.merge(df1, cpi_f, left_on=['Year','Month'], right_on=['year','cpi_month'])

In [38]:
combined.describe()

,Year,Month,"Alcoholic beverages at home in U.S. city average, all urban consumers, not seasonally adjusted","Beef and veal in U.S. city average, all urban consumers, not seasonally adjusted","Breakfast cereal in U.S. city average, all urban consumers, not seasonally adjusted","Cakes, cupcakes, and cookies in U.S. city average, all urban consumers, not seasonally adjusted","Carbonated drinks in U.S. city average, all urban consumers, not seasonally adjusted","Cereals and cereal products in U.S. city average, all urban consumers, not seasonally adjusted","Dairy and related products in U.S. city average, all urban consumers, not seasonally adjusted","Fats and oils in U.S. city average, all urban consumers, not seasonally adjusted","Fish and seafood in U.S. city average, all urban consumers, not seasonally adjusted","Flour and prepared flour mixes in U.S. city average, all urban consumers, not seasonally adjusted","Food in U.S. city average, all urban consumers, not seasonally adjusted","Frozen vegetables in U.S. city average, all urban consumers, not seasonally adjusted","Fruits and vegetables in U.S. city average, all urban consumers, not seasonally adjusted","Ham in U.S. city average, all urban consumers, not seasonally adjusted","Meats in U.S. city average, all urban consumers, not seasonally adjusted","Poultry in U.S. city average, all urban consumers, not seasonally adjusted","Rice, pasta, cornmeal in U.S. city average, all urban consumers, not seasonally adjusted"
count,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000
mean,2000.753247,6.461039,158.118225,183.909459,186.253883,196.693844,130.491379,177.216110,163.533955,163.000513,196.953656,173.170491,176.660745,159.554167,210.495290,159.071866,170.560379,169.390455,167.815439
std,11.127916,3.455574,33.758970,72.671277,40.157365,60.600935,22.582663,43.432121,43.363523,44.833483,61.242186,52.267273,50.817911,35.984652,68.433349,36.479032,53.861898,44.568401,50.930526
min,1982.000000,1.000000,95.000000,95.000000,93.100000,94.200000,96.700000,96.800000,98.300000,95.500000,96.800000,97.800000,95.800000,93.300000,91.900000,93.400000,96.000000,93.500000,97.800000
25%,1991.000000,3.000000,138.450000,131.900000,168.500000,151.175000,113.725000,148.050000,127.075000,129.800000,149.425000,127.375000,136.550000,129.775000,153.750000,134.950000,131.100000,133.150000,126.650000
50%,2001.000000,6.000000,160.550000,159.650000,198.750000,191.050000,124.100000,177.950000,164.000000,153.250000,189.200000,165.100000,171.800000,164.450000,211.650000,157.400000,157.950000,162.450000,153.650000
75%,2010.000000,9.000000,191.295250,229.569750,218.227250,252.207250,156.411000,222.590500,210.555250,206.842000,247.939000,231.202500,220.616750,196.582250,280.984250,191.971500,211.844750,206.094750,231.166000
max,2020.000000,12.000000,209.557000,385.495000,231.909000,298.935000,182.446000,236.930000,230.166000,234.392000,313.424000,258.791000,269.770000,212.813000,306.798000,239.559000,298.033000,252.765000,249.304000

In [39]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 462 entries, 0 to 461
Data columns (total 26 columns):
 #   Column                                                                                             Non-Null Count  Dtype
---  ------                                                                                             --------------  -----
 0   Month_Year                                                                                         462 non-null    object
 1   Corn                                                                                               461 non-null    object
 2   Ethanol                                                                                            462 non-null    object
 3   Blender_cost                                                                                       462 non-null    object
 4   Gasoline                                                                                           462 non-null    object
 5   Corn_cost_per_gallon                                                                               462 non-null    object
 6   Ethanol_geg                                                                                        462 non-null    object
 7   Year                                                                                               462 non-null    int64
 8   Month                                                                                              462 non-null    int64
 9   Alcoholic beverages at home in U.S. city average, all urban consumers, not seasonally adjusted     462 non-null    float64
 10  Beef and veal in U.S. city average, all urban consumers, not seasonally adjusted                   462 non-null    float64
 11  Breakfast cereal in U.S. city average, all urban consumers, not seasonally adjusted                462 non-null    float64
 12  Cakes, cupcakes, and cookies in U.S. city average, all urban consumers, not seasonally adjusted    462 non-null    float64
 13  Carbonated drinks in U.S. city average, all urban consumers, not seasonally adjusted               462 non-null    float64
 14  Cereals and cereal products in U.S. city average, all urban consumers, not seasonally adjusted     462 non-null    float64
 15  Dairy and related products in U.S. city average, all urban consumers, not seasonally adjusted      462 non-null    float64
 16  Fats and oils in U.S. city average, all urban consumers, not seasonally adjusted                   462 non-null    float64
 17  Fish and seafood in U.S. city average, all urban consumers, not seasonally adjusted                462 non-null    float64
 18  Flour and prepared flour mixes in U.S. city average, all urban consumers, not seasonally adjusted  462 non-null    float64
 19  Food in U.S. city average, all urban consumers, not seasonally adjusted                            462 non-null    float64
 20  Frozen vegetables in U.S. city average, all urban consumers, not seasonally adjusted               462 non-null    float64
 21  Fruits and vegetables in U.S. city average, all urban consumers, not seasonally adjusted           462 non-null    float64
 22  Ham in U.S. city average, all urban consumers, not seasonally adjusted                             462 non-null    float64
 23  Meats in U.S. city average, all urban consumers, not seasonally adjusted                           462 non-null    float64
 24  Poultry in U.S. city average, all urban consumers, not seasonally adjusted                         462 non-null    float64
 25  Rice, pasta, cornmeal in U.S. city average, all urban consumers, not seasonally adjusted           462 non-null    float64
dtypes: float64(17), int64(2), object(7)
memory usage: 97.5+ KB

In [40]:
# for loop to change all values to numeric except for Month_Year
for i in combined.columns:
    if i != 'Month_Year':
        combined[i] = pd.to_numeric(combined[i])

In [41]:
# check data types
combined.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 462 entries, 0 to 461
Data columns (total 26 columns):
 #   Column                                                                                             Non-Null Count  Dtype
---  ------                                                                                             --------------  -----
 0   Month_Year                                                                                         462 non-null    object
 1   Corn                                                                                               461 non-null    float64
 2   Ethanol                                                                                            462 non-null    float64
 3   Blender_cost                                                                                       462 non-null    float64
 4   Gasoline                                                                                           462 non-null    float64
 5   Corn_cost_per_gallon                                                                               462 non-null    float64
 6   Ethanol_geg                                                                                        462 non-null    float64
 7   Year                                                                                               462 non-null    int64
 8   Month                                                                                              462 non-null    int64
 9   Alcoholic beverages at home in U.S. city average, all urban consumers, not seasonally adjusted     462 non-null    float64
 10  Beef and veal in U.S. city average, all urban consumers, not seasonally adjusted                   462 non-null    float64
 11  Breakfast cereal in U.S. city average, all urban consumers, not seasonally adjusted                462 non-null    float64
 12  Cakes, cupcakes, and cookies in U.S. city average, all urban consumers, not seasonally adjusted    462 non-null    float64
 13  Carbonated drinks in U.S. city average, all urban consumers, not seasonally adjusted               462 non-null    float64
 14  Cereals and cereal products in U.S. city average, all urban consumers, not seasonally adjusted     462 non-null    float64
 15  Dairy and related products in U.S. city average, all urban consumers, not seasonally adjusted      462 non-null    float64
 16  Fats and oils in U.S. city average, all urban consumers, not seasonally adjusted                   462 non-null    float64
 17  Fish and seafood in U.S. city average, all urban consumers, not seasonally adjusted                462 non-null    float64
 18  Flour and prepared flour mixes in U.S. city average, all urban consumers, not seasonally adjusted  462 non-null    float64
 19  Food in U.S. city average, all urban consumers, not seasonally adjusted                            462 non-null    float64
 20  Frozen vegetables in U.S. city average, all urban consumers, not seasonally adjusted               462 non-null    float64
 21  Fruits and vegetables in U.S. city average, all urban consumers, not seasonally adjusted           462 non-null    float64
 22  Ham in U.S. city average, all urban consumers, not seasonally adjusted                             462 non-null    float64
 23  Meats in U.S. city average, all urban consumers, not seasonally adjusted                           462 non-null    float64
 24  Poultry in U.S. city average, all urban consumers, not seasonally adjusted                         462 non-null    float64
 25  Rice, pasta, cornmeal in U.S. city average, all urban consumers, not seasonally adjusted           462 non-null    float64
dtypes: float64(23), int64(2), object(1)
memory usage: 97.5+ KB

In [42]:
#shorten column names
combined.columns = combined.columns.str.replace(' in U.S. city average, all urban consumers, not seasonally adjusted', '')

In [43]:
# get summary statistics
combined.describe()

,Corn,Ethanol,Blender_cost,Gasoline,Corn_cost_per_gallon,Ethanol_geg,Year,Month,Alcoholic beverages at home,Beef and veal,...,Fats and oils,Fish and seafood,Flour and prepared flour mixes,Food,Frozen vegetables,Fruits and vegetables,Ham,Meats,Poultry,"Rice, pasta, cornmeal"
count,461.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,...,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000
mean,3.028091,1.567684,1.142835,1.310152,1.109388,2.339827,2000.753247,6.461039,158.118225,183.909459,...,163.000513,196.953656,173.170491,176.660745,159.554167,210.495290,159.071866,170.560379,169.390455,167.815439
std,1.242822,0.515385,0.612010,0.811615,0.468614,0.769231,11.127916,3.455574,33.758970,72.671277,...,44.833483,61.242186,52.267273,50.817911,35.984652,68.433349,36.479032,53.861898,44.568401,50.930526
min,1.400000,0.590000,0.150000,0.360000,0.218519,0.880597,1982.000000,1.000000,95.000000,95.000000,...,95.500000,96.800000,97.800000,95.800000,93.300000,91.900000,93.400000,96.000000,93.500000,97.800000
25%,2.170000,1.182500,0.650000,0.630000,0.796296,1.764925,1991.000000,3.000000,138.450000,131.900000,...,129.800000,149.425000,127.375000,136.550000,129.775000,153.750000,134.950000,131.100000,133.150000,126.650000
50%,2.600000,1.430000,0.980000,0.940000,0.955556,2.134328,2001.000000,6.000000,160.550000,159.650000,...,153.250000,189.200000,165.100000,171.800000,164.450000,211.650000,157.400000,157.950000,162.450000,153.650000
75%,3.560000,1.720000,1.517500,1.927500,1.317593,2.567164,2010.000000,9.000000,191.295250,229.569750,...,206.842000,247.939000,231.202500,220.616750,196.582250,280.984250,191.971500,211.844750,206.094750,231.166000
max,7.630000,3.580000,3.150000,3.370000,2.825926,5.343284,2020.000000,12.000000,209.557000,385.495000,...,234.392000,313.424000,258.791000,269.770000,212.813000,306.798000,239.559000,298.033000,252.765000,249.304000

In [44]:
combined['Date'] = pd.to_datetime(combined[['Month', 'Year']].assign(Day=1))

In [45]:
combined.Date

0     1982-01-01
1     1982-02-01
2     1982-03-01
3     1982-04-01
4     1982-05-01
         ...
457   2020-02-01
458   2020-03-01
459   2020-04-01
460   2020-05-01
461   2020-06-01
Name: Date, Length: 462, dtype: datetime64[ns]

In [46]:
combined = combined.set_index('Date')

In [47]:
combined = combined.drop(['Month_Year'], 1)

In [48]:
combined.head(20)

,Corn,Ethanol,Blender_cost,Gasoline,Corn_cost_per_gallon,Ethanol_geg,Year,Month,Alcoholic beverages at home,Beef and veal,...,Fats and oils,Fish and seafood,Flour and prepared flour mixes,Food,Frozen vegetables,Fruits and vegetables,Ham,Meats,Poultry,"Rice, pasta, cornmeal"
Date,,,,,,,,,,,,,,,,,,,,,
1982-01-01,2.54,1.75,1.15,1.04,0.940741,2.611940,1982,1,95.0,98.0,...,96.8,98.9,97.8,95.8,93.3,98.1,94.4,96.0,95.3,102.0
1982-02-01,2.44,1.70,1.10,1.01,0.903704,2.537313,1982,2,95.8,98.8,...,96.4,99.0,97.8,96.6,94.0,100.4,94.3,96.9,96.1,102.9
1982-03-01,2.46,1.66,1.06,0.95,0.911111,2.477612,1982,3,96.3,98.9,...,96.1,99.7,97.9,96.4,94.2,97.6,95.8,97.3,95.6,102.1
1982-04-01,2.55,1.70,1.10,0.90,0.944444,2.537313,1982,4,96.7,100.0,...,96.4,101.2,98.2,96.8,95.5,97.9,93.4,98.2,94.9,101.0
1982-05-01,2.60,1.70,1.10,0.94,0.962963,2.537313,1982,5,97.0,102.3,...,96.4,97.0,99.7,97.3,95.5,99.2,97.1,100.4,96.2,101.4
1982-06-01,2.57,1.70,1.10,1.05,0.951852,2.537313,1982,6,97.0,104.9,...,96.5,96.8,99.9,98.1,96.6,101.8,98.4,103.2,97.0,100.9
1982-07-01,2.50,1.70,1.10,1.06,0.925926,2.537313,1982,7,97.4,104.3,...,96.0,98.1,100.9,98.3,97.3,99.8,100.3,103.8,98.0,100.5
1982-08-01,2.30,1.70,1.10,1.05,0.851852,2.537313,1982,8,97.8,102.1,...,95.6,97.4,99.5,97.9,98.0,97.0,101.4,103.0,96.3,100.8
1982-09-01,2.15,1.70,1.10,1.03,0.796296,2.537313,1982,9,97.7,101.6,...,95.6,97.9,99.4,98.0,98.2,94.6,104.6,103.7,96.3,100.1
1982-10-01,1.98,1.69,1.09,1.02,0.733333,2.522388,1982,10,97.9,99.1,...,95.6,97.3,98.3,97.8,98.0,93.5,108.2,102.4,95.9,99.7
1982-11-01,2.13,1.72,1.12,0.99,0.788889,2.567164,1982,11,97.9,99.0,...,95.7,97.1,97.9,97.6,98.8,91.9,109.1,101.9,94.3,98.7
1982-12-01,2.26,1.75,1.15,0.96,0.837037,2.611940,1982,12,97.8,98.3,...,95.7,97.9,98.1,97.6,97.8,92.4,110.7,101.0,93.5,98.1
1983-01-01,2.36,1.69,1.09,0.92,0.874074,2.522388,1983,1,98.1,98.7,...,96.0,99.8,98.6,98.2,99.3,92.0,110.8,101.4,93.9,98.9
1983-02-01,2.56,1.68,1.08,0.88,0.948148,2.507463,1983,2,99.0,99.1,...,95.5,100.5,98.3,98.5,100.3,92.6,108.6,101.7,95.2,98.1
1983-03-01,2.71,1.64,1.04,0.86,1.003704,2.447761,1983,3,100.0,99.3,...,95.6,100.7,98.0,99.0,99.3,95.5,109.1,101.6,95.1,98.6
1983-04-01,2.95,1.70,1.10,0.90,1.092593,2.537313,1983,4,100.4,101.7,...,95.7,100.5,98.6,99.5,100.1,98.2,103.4,101.8,93.8,98.5
1983-05-01,3.03,1.70,1.10,0.94,1.122222,2.537313,1983,5,100.6,102.4,...,95.6,98.7,99.3,99.7,100.3,99.3,100.0,101.6,94.3,97.8
1983-06-01,3.04,1.70,1.10,0.95,1.125926,2.537313,1983,6,100.8,101.4,...,95.6,98.3,100.0,99.5,100.4,99.3,98.2,100.6,95.0,98.7
1983-07-01,3.13,1.70,1.10,0.95,1.159259,2.537313,1983,7,101.1,100.4,...,95.8,97.7,100.4,99.5,100.6,99.5,96.5,99.7,97.3,98.9
1983-08-01,3.35,1.73,1.13,0.95,1.240741,2.582090,1983,8,100.8,98.5,...,95.5,98.7,101.2,99.6,101.4,99.7,96.9,98.4,98.4,98.3

In [49]:
FoodFuel = combined.to_csv('FoodFuel.csv', index=True)